// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiFinalKwiecinskiJoel.Data;

namespace WebApiFinalKwiecinskiJoel.Migrations
{
    [DbContext(typeof(DbHospitalAPIContext))]
    partial class DbHospitalAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiFinalKwiecinskiJoel.Models.Doctor", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Especialidad")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("HospitalCod")
                        .HasColumnType("int");

                    b.HasKey("No");

                    b.HasIndex("HospitalCod");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("WebApiFinalKwiecinskiJoel.Models.Hospital", b =>
                {
                    b.Property<int>("HospitalCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Num_Cama")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(50)");

                    b.HasKey("HospitalCod");

                    b.ToTable("Hospital");
                });

            modelBuilder.Entity("WebApiFinalKwiecinskiJoel.Models.Doctor", b =>
                {
                    b.HasOne("WebApiFinalKwiecinskiJoel.Models.Hospital", "Hospital")
                        .WithMany("Doctors")
                        .HasForeignKey("HospitalCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
